[package]
name = "go-rs-bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "rslib"
crate-type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
